import { YearSummary } from '../services/ParametersService';
import { ParametersState } from '../redux/slices/ParametersSlice';
import { DAY, MonthsArray } from '../services/CalendarService';
import { IncomeTaxesSummary } from '../services/TaxesService';

export const parameters: ParametersState = {
    selectedMonths: MonthsArray,
    averageDailyRate: 550,
    year: 2022,
    vatRate: 20,
    taxAllowance: 34,
    socialContribution: [
        { rate: 22.2, label: 'Prestations de services (bnc et bic) et vente de marchandises (bic)' },
        { rate: 0.2, label: 'Formation prof.liberale obligatoire' },
    ],
    taxationFamilyContext: {
        incomeSplittingParts: 3,
        taxableHouseholdRevenues: 24506,
        taxAllowance: 10,
    },
    saving: { mode: 'percentage', value: 20 },
    partTime: { percentage: 100 },
    dayOffContext: { unit: 'weeks', value: 5 },
    nonWorkingDays: [DAY.SATURDAY, DAY.SUNDAY],
};

export const expectedYearSummary: YearSummary = {
    monthSummaries: [
        {
            month: 0,
            totalDays: 19,
            revenue: 10450,
            vat: 2090,
            includingTax: 12540,
            socialContribution: 2341,
            profits: 8109,
        },
        {
            month: 1,
            totalDays: 18,
            revenue: 9900,
            vat: 1980,
            includingTax: 11880,
            socialContribution: 2218,
            profits: 7682,
        },
        {
            month: 2,
            totalDays: 21,
            revenue: 11550,
            vat: 2310,
            includingTax: 13860,
            socialContribution: 2587,
            profits: 8963,
        },
        {
            month: 3,
            totalDays: 19,
            revenue: 10450,
            vat: 2090,
            includingTax: 12540,
            socialContribution: 2341,
            profits: 8109,
        },
        {
            month: 4,
            totalDays: 20,
            revenue: 11000,
            vat: 2200,
            includingTax: 13200,
            socialContribution: 2464,
            profits: 8536,
        },
        {
            month: 5,
            totalDays: 20,
            revenue: 11000,
            vat: 2200,
            includingTax: 13200,
            socialContribution: 2464,
            profits: 8536,
        },
        {
            month: 6,
            totalDays: 19,
            revenue: 10450,
            vat: 2090,
            includingTax: 12540,
            socialContribution: 2341,
            profits: 8109,
        },
        {
            month: 7,
            totalDays: 21,
            revenue: 11550,
            vat: 2310,
            includingTax: 13860,
            socialContribution: 2587,
            profits: 8963,
        },
        {
            month: 8,
            totalDays: 20,
            revenue: 11000,
            vat: 2200,
            includingTax: 13200,
            socialContribution: 2464,
            profits: 8536,
        },
        {
            month: 9,
            totalDays: 19,
            revenue: 10450,
            vat: 2090,
            includingTax: 12540,
            socialContribution: 2341,
            profits: 8109,
        },
        {
            month: 10,
            totalDays: 20,
            revenue: 11000,
            vat: 2200,
            includingTax: 13200,
            socialContribution: 2464,
            profits: 8536,
        },
        {
            month: 11,
            totalDays: 19,
            revenue: 10450,
            vat: 2090,
            includingTax: 12540,
            socialContribution: 2341,
            profits: 8109,
        },
    ],
    totals: {
        totalDays: 235,
        includingTax: 155100,
        socialContribution: 28953,
        vat: 25850,
        profits: 100297,
        revenue: 129250,
    },
};
export const expectedIncomeTaxesSummaryAlone: IncomeTaxesSummary = {
    taxBracketSummaries: [
        { bracket: { bottomBracket: 0, topBracket: 10225, rate: 0 }, amount: 0 },
        { bracket: { bottomBracket: 10226, topBracket: 26070, rate: 11 }, amount: 1743 },
        { bracket: { bottomBracket: 26071, topBracket: 74545, rate: 30 }, amount: 11979 },
        { bracket: { bottomBracket: 74546, topBracket: 160336, rate: 41 }, amount: 0 },
        { bracket: { bottomBracket: 160336, rate: 45 }, amount: 0 },
    ],
    netTaxableIncome: {
        contractorNetTaxableIncome: 66000,
        familyNetTaxableIncome: 0,
        incomeSplittingParts: 1,
        netTaxableIncomeResult: 66000,
    },
    total: 13722,
};
